name: aic
services:
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    # image: my-eval:v1
    build:
      dockerfile: docker/aic_eval/Dockerfile
      context: ..
    command: gazebo_gui:=true launch_rviz:=true ground_truth:=false start_aic_engine:=true shutdown_on_aic_engine_exit:=true model_discovery_timeout_seconds:=600
    gpus: all
    networks:
      - default
    environment:
      AIC_EVAL_PASSWD: CHANGE_IN_PROD
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
  model:
    image: baseline:v1
    build:
      dockerfile: ws_aic/src/aic/docker/my_policy_node/Dockerfile
      context: ../../../..
    gpus: all
    networks:
      - default
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
      AIC_ROUTER_ADDR: eval:7447
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
      AIC_YOLO_DEVICE: ${AIC_YOLO_DEVICE:-cpu}
networks:
  default:
    internal: true
