name: aic
services:
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    # image: my-eval:v1
    build:
      dockerfile: docker/aic_eval/Dockerfile
      context: ..
    command: gazebo_gui:=false launch_rviz:=false ground_truth:=false start_aic_engine:=true shutdown_on_aic_engine_exit:=true model_discovery_timeout_seconds:=600
    gpus: all
    networks:
      - default
    volumes:
      - /home/swlinux/aic_results/${RUN_TAG:-default}:/aic_results
    environment:
      AIC_EVAL_PASSWD: CHANGE_IN_PROD
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
      AIC_RESULTS_DIR: /aic_results
  model:
    image: ais-policy:latest
    build:
      dockerfile: ws_aic/src/ais/docker/ais_policy/Dockerfile
      context: ../../../..
    gpus: all
    networks:
      - default
    volumes:
      - /home/swlinux/AIC_Sejong/debug:/debug/yolo_detections
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
      AIC_ROUTER_ADDR: eval:7447
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
      AIC_DEBUG_SAVE_DIR: /debug/yolo_detections
      AIC_DISTANCE_LABEL_PORT_FRAME_MODE: ${AIC_DISTANCE_LABEL_PORT_FRAME_MODE:-link}
      AIC_DISTANCE_ALIGN_USE_PORT_FRAME_ROTATION: ${AIC_DISTANCE_ALIGN_USE_PORT_FRAME_ROTATION:-false}
      AIC_DISTANCE_ALIGN_CORRECTION_X_SIGN: ${AIC_DISTANCE_ALIGN_CORRECTION_X_SIGN:--1.0}
      AIC_DISTANCE_ALIGN_CORRECTION_Y_SIGN: ${AIC_DISTANCE_ALIGN_CORRECTION_Y_SIGN:--1.0}
      AIC_DISTANCE_ALIGN_RETRY_ENABLED: ${AIC_DISTANCE_ALIGN_RETRY_ENABLED:-true}
      AIC_DISTANCE_ALIGN_RETRY_FORCE_XY_THRESHOLD_N: ${AIC_DISTANCE_ALIGN_RETRY_FORCE_XY_THRESHOLD_N:-2.0}
      AIC_DISTANCE_ALIGN_RETRY_FORCE_Z_THRESHOLD_N: ${AIC_DISTANCE_ALIGN_RETRY_FORCE_Z_THRESHOLD_N:-4.0}
      AIC_DISTANCE_ALIGN_RETRY_LATERAL_STEP_M: ${AIC_DISTANCE_ALIGN_RETRY_LATERAL_STEP_M:-0.002}
      AIC_DISTANCE_ALIGN_RETRY_LIFT_M: ${AIC_DISTANCE_ALIGN_RETRY_LIFT_M:-0.005}
      AIC_DISTANCE_ALIGN_RETRY_FORCE_X_SIGN: ${AIC_DISTANCE_ALIGN_RETRY_FORCE_X_SIGN:--1.0}
      AIC_DISTANCE_ALIGN_RETRY_FORCE_Y_SIGN: ${AIC_DISTANCE_ALIGN_RETRY_FORCE_Y_SIGN:--1.0}
networks:
  default:
    internal: true
