#!/usr/bin/env python3
"""PortOffset 범위의 triangulation case YAML을 만들고 AIC simulator를 실행한다."""

from __future__ import annotations

import argparse
import os
import random
import re
import shlex
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any, Sequence

import yaml


TRIANGULATION_ROOT = Path(__file__).resolve().parent
AIS_ROOT = TRIANGULATION_ROOT.parent
AUTO_CAPTURE_ROOT = AIS_ROOT / "ais_auto_capture"
if str(AUTO_CAPTURE_ROOT) not in sys.path:
    sys.path.insert(0, str(AUTO_CAPTURE_ROOT))

from portoffset_randomization.constants import CLI_DEFAULTS  
from portoffset_randomization.scenario import make_trial_config  


BOLD_MAGENTA = "\033[1;35m"
BOLD_GREEN = "\033[1;32m"
ANSI_RESET = "\033[0m"


def _bold_log(color: str, message: str) -> None:
    """중요 runner 상태를 ANSI bold/color로 출력한다."""
    print(f"{color}{message}{ANSI_RESET}", flush=True)


def _parse_bool(value: str) -> bool:
    """CLI의 true/false 문자열을 boolean으로 변환한다."""
    normalized = str(value).strip().lower()
    if normalized == "true":
        return True
    if normalized == "false":
        return False
    raise argparse.ArgumentTypeError("expected true or false")


def _parse_sim_arg(value: str) -> tuple[str, str]:
    """추가 simulator launch argument를 NAME=VALUE 튜플로 파싱한다."""
    token = str(value).strip()
    separator = ":=" if ":=" in token else "="
    if separator not in token:
        raise argparse.ArgumentTypeError("expected NAME=VALUE or NAME:=VALUE")
    name, raw_value = token.split(separator, 1)
    name = name.strip()
    raw_value = raw_value.strip()
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", name):
        raise argparse.ArgumentTypeError(f"invalid launch argument name: {name!r}")
    if not raw_value:
        raise argparse.ArgumentTypeError("simulator launch argument value is empty")
    return name, raw_value


def _ros_value(value: Any) -> str:
    """Python boolean은 ROS launch 형식의 소문자 문자열로 변환한다."""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _scenario_args(args: argparse.Namespace) -> argparse.Namespace:
    """PortOffset generator가 사용하는 CLI 값 중 scene 관련 값을 전달한다."""
    return argparse.Namespace(
        port_types=args.port_types,
        port_order=args.port_order,
        time_limit_s=args.time_limit_s,
        robot_joint_noise_deg=args.robot_joint_noise_deg,
        cable_rpy_noise_deg=args.cable_rpy_noise_deg,
    )


def generate_cases(
    *,
    seed: int,
    num_cases: int,
    scenario_args: argparse.Namespace,
) -> dict[str, Any]:
    """PortOffset와 같은 generator/RNG로 multi-trial AIC config를 만든다."""
    if num_cases <= 0:
        raise ValueError("num_cases must be greater than zero")

    rng = random.Random(seed)
    generated = [
        make_trial_config(index, rng, scenario_args)
        for index in range(num_cases)
    ]
    first_config = generated[0][0]
    trials: dict[str, Any] = {}
    for config, _metadata in generated:
        trials.update(config["trials"])

    # AIC multi-trial schema has one global robot section. The first PortOffset
    # draw is therefore shared by every trial; all board/module/cable values are
    # still sampled independently by the original PortOffset generator.
    return {
        "scoring": first_config["scoring"],
        "task_board_limits": first_config["task_board_limits"],
        "trials": trials,
        "robot": first_config["robot"],
    }


def default_output_path(today: date | None = None) -> Path:
    """날짜 기반 기본 YAML 경로를 반환한다."""
    stamp = (today or date.today()).strftime("%Y%m%d")
    return TRIANGULATION_ROOT / "cases" / f"{stamp}_triangulation_cases.yaml"


def write_cases(
    path: Path,
    config: dict[str, Any],
    *,
    seed: int,
    num_cases: int,
) -> None:
    """재현 정보가 포함된 AIC engine YAML을 저장한다."""
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by run_triangulation_cases.py\n"
        f"# seed: {seed}\n"
        f"# num_cases: {num_cases}\n"
        "# robot pose: first generated case, shared by the multi-trial engine config\n"
    )
    path.write_text(
        header + yaml.safe_dump(config, sort_keys=False),
        encoding="utf-8",
    )


def simulator_command(args: argparse.Namespace, cases_path: Path) -> list[str]:
    """생성 YAML을 실행할 Distrobox 명령을 구성한다."""
    launch_arguments = [
        ("ground_truth", args.ground_truth),
        ("start_aic_engine", args.start_aic_engine),
        ("gazebo_gui", args.gazebo_gui),
        ("launch_rviz", args.launch_rviz),
        ("spawn_task_board", args.spawn_task_board),
        ("spawn_cable", args.spawn_cable),
    ]
    launch_arguments.extend(args.sim_arg)
    launch_arguments.append(
        ("aic_engine_config_file", str(cases_path.resolve()))
    )
    return [
        "distrobox",
        "enter",
        args.distrobox,
        "--",
        "/entrypoint.sh",
        *(f"{name}:={_ros_value(value)}" for name, value in launch_arguments),
    ]


def run_simulator(args: argparse.Namespace, cases_path: Path) -> None:
    """Docker backend의 Distrobox에서 AIC simulator를 실행한다."""
    command = simulator_command(args, cases_path)
    env = os.environ.copy()
    env["DBX_CONTAINER_MANAGER"] = "docker"
    _bold_log(BOLD_GREEN, f"[simulator start] {shlex.join(command)}")
    subprocess.run(command, env=env, check=True)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate PortOffset-range triangulation cases and run them in aic_eval."
        )
    )
    parser.add_argument("--seed", type=int, default=CLI_DEFAULTS["seed"])
    parser.add_argument(
        "--num-cases",
        "--num_cases",
        dest="num_cases",
        type=int,
        default=CLI_DEFAULTS["trials"],
        help="number of randomized cases (must be > 0)",
    )
    parser.add_argument("--port-types", default=CLI_DEFAULTS["port_types"])
    parser.add_argument(
        "--port-order",
        choices=("round_robin", "random"),
        default=CLI_DEFAULTS["port_order"],
    )
    parser.add_argument(
        "--time-limit-s",
        type=int,
        default=CLI_DEFAULTS["time_limit_s"],
    )
    parser.add_argument(
        "--robot-joint-noise-deg",
        type=float,
        default=CLI_DEFAULTS["robot_joint_noise_deg"],
    )
    parser.add_argument(
        "--cable-rpy-noise-deg",
        type=float,
        default=CLI_DEFAULTS["cable_rpy_noise_deg"],
    )
    parser.add_argument("--distrobox", default=CLI_DEFAULTS["distrobox"])
    parser.add_argument(
        "--headless",
        action="store_true",
        help="legacy shortcut for --gazebo_gui false",
    )
    parser.add_argument(
        "--ground-truth",
        "--ground_truth",
        dest="ground_truth",
        type=_parse_bool,
        default=True,
        metavar="{true,false}",
    )
    parser.add_argument(
        "--start-aic-engine",
        "--start_aic_engine",
        dest="start_aic_engine",
        type=_parse_bool,
        default=True,
        metavar="{true,false}",
    )
    parser.add_argument(
        "--gazebo-gui",
        "--gazebo_gui",
        dest="gazebo_gui",
        type=_parse_bool,
        default=False,
        metavar="{true, false}",
    )
    parser.add_argument(
        "--launch-rviz",
        "--launch_rviz",
        dest="launch_rviz",
        type=_parse_bool,
        default=False,
        metavar="{true,false}",
    )
    parser.add_argument(
        "--spawn-task-board",
        "--spawn_task_board",
        dest="spawn_task_board",
        type=_parse_bool,
        default=False,
        metavar="{true,false}",
    )
    parser.add_argument(
        "--spawn-cable",
        "--spawn_cable",
        dest="spawn_cable",
        type=_parse_bool,
        default=False,
        metavar="{true,false}",
    )
    parser.add_argument(
        "--sim-arg",
        action="append",
        type=_parse_sim_arg,
        default=[],
        metavar="NAME=VALUE",
        help="additional /entrypoint.sh launch argument; may be repeated",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="output YAML (default: cases/YYYYMMDD_triangulation_cases.yaml)",
    )
    parser.add_argument(
        "--generate-only",
        action="store_true",
        help="write YAML without launching Distrobox",
    )
    args = parser.parse_args(argv)
    if args.num_cases <= 0:
        parser.error("--num-cases/--num_cases must be greater than zero")
    if args.headless and args.gazebo_gui is True:
        parser.error("--headless conflicts with --gazebo-gui/--gazebo_gui true")
    if args.headless:
        args.gazebo_gui = False
    elif args.gazebo_gui is None:
        args.gazebo_gui = True

    reserved_sim_args = {
        "ground_truth",
        "start_aic_engine",
        "gazebo_gui",
        "launch_rviz",
        "spawn_task_board",
        "spawn_cable",
        "aic_engine_config_file",
    }
    duplicated = sorted(
        name for name, _value in args.sim_arg if name in reserved_sim_args
    )
    if duplicated:
        parser.error(
            "--sim-arg duplicates explicit option(s): " + ", ".join(duplicated)
        )
    return args


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)
    output = (args.output or default_output_path()).expanduser().resolve()
    config = generate_cases(
        seed=args.seed,
        num_cases=args.num_cases,
        scenario_args=_scenario_args(args),
    )
    write_cases(output, config, seed=args.seed, num_cases=args.num_cases)
    _bold_log(
        BOLD_MAGENTA,
        f"[generated] cases={args.num_cases} seed={args.seed} yaml={output}",
    )
    if not args.generate_only:
        run_simulator(args, output)


if __name__ == "__main__":
    main()
